name: Build Minicraft PS2
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PS2DEV: /usr/local/ps2dev
      PS2SDK: /usr/local/ps2dev/ps2sdk
      GSKIT: /usr/local/ps2dev/gsKit
    steps:
      - uses: actions/checkout@v4
      - name: Install ps2dev prebuilt
        run: |
          curl -o ps2dev.tar.gz -L https://github.com/ps2dev/ps2dev/releases/download/latest/ps2dev-ubuntu-latest.tar.gz
          sudo tar -xzf ps2dev.tar.gz --strip-components 1 -C /usr/local
          echo "/usr/local/ps2dev/bin" >> $GITHUB_PATH
          echo "/usr/local/ps2dev/ee/bin" >> $GITHUB_PATH
          echo "/usr/local/ps2dev/iop/bin" >> $GITHUB_PATH
          echo "/usr/local/ps2dev/dvp/bin" >> $GITHUB_PATH
          echo "/usr/local/ps2dev/ps2sdk/bin" >> $GITHUB_PATH
      - name: Fix missing Makefile helpers
        run: |
          sudo mkdir -p /usr/local/ps2dev/ps2sdk/samples
          curl -o Makefile.pref -L https://raw.githubusercontent.com/ps2dev/ps2sdk/master/samples/Makefile.pref_sample
          curl -o Makefile.eeglobal -L https://raw.githubusercontent.com/ps2dev/ps2sdk/master/samples/Makefile.eeglobal_sample
          sudo mv Makefile.pref /usr/local/ps2dev/ps2sdk/samples/Makefile.pref
          sudo mv Makefile.eeglobal /usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal
      - name: Build game
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: minicraft-elf
          path: minicraft.elf
