- name: Build game
        run: |
          ls /usr/local/ps2dev/ || echo "EMPTY"
          ls /usr/local/ || echo "EMPTY2"
          find /usr/local -name "*ps2-elf-gcc*" || echo "NOT FOUND"
          make
